name: merge-mods
run-name: Merge mods
on: push
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make the script file executable
        run: chmod +x ./merge-mods
      - name: Run the script
        run: ./merge-mods
      - name: Commit changes to repo
        run: |
          git config --global user.name 'Merge mods'
          git config --global user.email 'merge-mods@users.noreply.github.com'
          git add build
          git commit -am 'action: Merge mods'
          git push
